name: RunIt
on: [push]

permissions:
    id-token: write
    contents: read

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: OIDC Login to Azure
            uses: azure/login@v2
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.9.7
              terraform_wrapper: false

          - name: Terraform Init
            env:
              ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
            id: terraform-init
            run: terraform init

          - name: Terraform Plan
            env:
              ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
            id: terraform-plan
            run: terraform plan

            - name: Terraform Apply
            env:
              ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
            id: terraform-apply
            run: terraform apply
